# Generated by Django 5.1.5 on 2025-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.PositiveIntegerField(
                default=12345, verbose_name="ID чата в Telegram"
            ),
            preserve_default=False,
        ),
    ]
