# Generated by Django 5.1.5 on 2025-01-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
