#services:
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#      - static_volume:/code/static
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - ./.env
#
#  db:
#    image: postgres:16
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    env_file:
#      - ./.env
#
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#
#  celery:
#    build: .
#    command: >
#      bash -c "celery -A config worker -l INFO -P eventlet"
#    env_file:
#      - ./.env
#    depends_on:
#      - redis
#      - db
#
#  celery_beat:
#    build: .
#    env_file:
#      - ./.env
#    command: >
#      bash -c "celery -A config beat -l INFO"
#    depends_on:
#      - redis
#      - db
#      - celery
#
#volumes:
#  postgres_data:
#  static_volume:
#  redis_data:

#####

#services:
#
#  web:
#    build: .
#    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/app
#      - static_volume:/app/staticfiles
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - ./.env
#
#  nginx:
#    build:
#      context: ./nginx
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - static_volume:/app/staticfiles
#    depends_on:
#      - web
#
#
#  db:
#    image: postgres:16
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - ./.env
#
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data env_file
#    env_file:
#      - ./.env
#
#
#  celery:
#    build: .
#    command: >
#      bash -c "celery -A config worker -l INFO -P eventlet"
#    env_file:
#      - ./.env
#    depends_on:
#      - redis
#      - db
#
#  celery_beat:
#    build: .
#    env_file:
#      - ./.env
#    command: >
#      bash -c "celery -A config beat -l INFO"
#    depends_on:
#      - redis
#      - db
#      - celery
#
#volumes:
#  postgres_data:
#  static_volume:
#  redis_data:
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod

  celery_beat:
    build:
      context: .
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Applying migrations...';
        python manage.py migrate &&
        echo 'Running load db.json' &&
        python manage.py loaddata db.json &&
        echo 'Starting Django server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    volumes:
      - .:/app

volumes:
  postgres_data: