version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: >
      bash -c "celery -A config worker -l INFO -P eventlet"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    env_file:
      - ./.env
    command: >
      bash -c "celery -A config beat -l INFO"
    depends_on:
      - redis
      - db
      - celery

volumes:
  postgres_data:
  static_volume:
  redis_data: