services:

  db:
    image: postgres:16
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data env_file
    env_file:
      - ./.env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  celery:
    build: .
    command: bash -c "celery -A config worker -l INFO"
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  celery_beat:
    build: .
    command: >
      bash -c "celery -A config beat -l INFO"
    depends_on:
      - redis
      - db
      - celery
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  redis_data:
