# Generated by Django 5.1.5 on 2025-01-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Место выполнения"),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневная"),
                            ("weekly", "Еженедельная"),
                            ("monthly", "Ежемесячная"),
                        ],
                        default="daily",
                        verbose_name="Переодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознагрождение",
                    ),
                ),
                (
                    "time_to_do",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Публичность"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
