# Generated by Django 5.1.5 on 2025-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
