# Generated by Django 5.1.5 on 2025-01-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habits",
                to="habit.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Переодичность"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.CharField(
                blank=True, null=True, verbose_name="Время выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_do",
            field=models.PositiveIntegerField(
                blank=True, default=120, null=True, verbose_name="Время на выполнение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
