# Generated by Django 5.1.5 on 2025-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_habit_is_pleasant_habit_related_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(default=1, verbose_name="Переодичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения"),
        ),
    ]
