# Generated by Django 5.1.5 on 2025-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_alter_habit_period_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Флаг приятности"
            ),
        ),
    ]
