# Generated by Django 5.1.5 on 2025-01-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0004_alter_habit_is_pleasant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habit.habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
    ]
