# Generated by Django 5.1.5 on 2025-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0005_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Вознаграждение"
            ),
        ),
    ]
