# Generated by Django 5.1.5 on 2025-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0006_alter_habit_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_indicator",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Индикатор отправки"
            ),
        ),
    ]
